const {
  NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY,
  NEXT_PUBLIC_BRAND = '',
  NEXT_PUBLIC_BRAND_LOGOTYPE = '',
  NEXT_PUBLIC_WA_MESSAGE = '',
  NEXT_PUBLIC_WHATSAPP = '',
  NEXT_PUBLIC_SITE_URL = '',
  NEXT_PUBLIC_WA_MESSAGE_TEMPLATE = '',
  GOOGLE_CLIENT_ID = '',
  GOOGLE_CLIENT_SECRET = '',
  GOOGLE_REDIRECT_URI = '',
} = process.env;

export const env = {
  whatsAppNumber: NEXT_PUBLIC_WHATSAPP,
  siteUrl: NEXT_PUBLIC_SITE_URL,
  waMessage: NEXT_PUBLIC_WA_MESSAGE,
  brand: NEXT_PUBLIC_BRAND,
  brandLogotype: NEXT_PUBLIC_BRAND_LOGOTYPE,
  waMessageTemplate: NEXT_PUBLIC_WA_MESSAGE_TEMPLATE,
  googleClientId: GOOGLE_CLIENT_ID,
  googleClientSecret: GOOGLE_CLIENT_SECRET,
  googleRedirectUri: GOOGLE_REDIRECT_URI,
  susap: {
    url: NEXT_PUBLIC_SUPABASE_URL || '',
    anonKey: NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
  },
} as const;
